tst_rend: models.o events.o raster.o rast_asm.o render.o tst_rend.o bitmaps.o
	cc68x -g models.o events.o raster.o rast_asm.o render.o tst_rend.o bitmaps.o -o tst_rend

tst_rend.o: tst_rend.c
	cc68x -g -c tst_rend.c

render.o: render.c render.h raster.h
	cc68x -g -c render.c

models.o: models.c models.h
	cc68x -g -c models.c

events.o: events.c events.h
	cc68x -g -c events.c
	
raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
