tst_model: tstmdl.o models.o events.o
	cc68x -g tstmdl.o models.o events.o -o tst_model

tstmdl.o: tstmdl.c tstmdl.h
	cc68x -g -c tstmdl.c

models.o: models.c models.h
	cc68x -g -c models.c

events.o: events.c events.h
	cc68x -g -c events.c
