
tstmodel: tstmodel.o models.o events.o raster.o
	cc68x -g tstmodel.o models.o events.o raster.o -o main

tstmodel.o: tstmodel.c models.o events.o
	cc68x -g -c tstmodel.c

models.o: models.c models.h
	cc68x -g -c models.c

events.o: events.c events.h
	cc68x -g -c events.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c




