geo_dash: models.o events.o raster.o rast_asm.o vbl.o kbd.o kbd_asm.o vbl_asm.o vct_inst.o input.o geo_dash.o bitmaps.o level.o effects.o music.o psg.o render.o vic.o vic_1.o vic_2.o vic_3.o vic_4.o vic_5.o vic_6.o vic_7.o vic_8.o vic_9.o super.o
	cc68x -g models.o events.o raster.o rast_asm.o vbl.o kbd.o render.o kbd_asm.o vbl_asm.o vct_inst.o input.o geo_dash.o bitmaps.o level.o effects.o music.o psg.o vic.o vic_1.o vic_2.o vic_3.o vic_4.o vic_5.o vic_6.o vic_7.o vic_8.o vic_9.o super.o -o geo_dash

geo_dash.o: geo_dash.c global.h
	cc68x -g -c geo_dash.c global.h

input.o: input.c input.h 
	cc68x -g -c input.c
	
render.o: render.c render.h raster.h 
	cc68x -g -c render.c

models.o: models.c models.h 
	cc68x -g -c models.c

level.o: Level.c Level.h 
	cc68x -g -c Level.c

events.o: events.c events.h 
	cc68x -g -c events.c
	
raster.o: raster.c raster.h 
	cc68x -g -c raster.c

bitmaps.o: bitmaps.c bitmaps.h 
	cc68x -g -c bitmaps.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

music.o: music.c music.h
	cc68x -g -c music.c

vct_inst.o: vct_inst.c vct_inst.h
	cc68x -g -c vct_inst.c

vbl.o: vbl.c vbl.h
	cc68x -g -c vbl.c

kbd.o: vbl.c kbd.h
	cc68x -g -c kbd.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

kbd_asm.o: kbd_asm.s
	gen -D -L2 kbd_asm.s

vbl_asm.o: vbl_asm.s
	gen -D -L2 vbl_asm.s

super.o: super.s
	gen -D -L2 super.s


vic.o: vic.c
	cc68x -g -c vic.c

vic_1.o: vic_1.c
	cc68x -g -c vic_1.c

vic_2.o: vic_2.c
	cc68x -g -c vic_2.c

vic_3.o: vic_3.c
	cc68x -g -c vic_3.c

vic_4.o: vic_4.c
	cc68x -g -c vic_4.c

vic_5.o: vic_5.c
	cc68x -g -c vic_5.c

vic_6.o: vic_6.c
	cc68x -g -c vic_6.c

vic_7.o: vic_7.c
	cc68x -g -c vic_7.c

vic_8.o: vic_8.c
	cc68x -g -c vic_8.c

vic_9.o: vic_9.c
	cc68x -g -c vic_9.c


