
main: main.o raster.o rast_asm.o
	cc68x -g main.o raster.o rast_asm.o  -o main

main.o: main.c raster.h
	cc68x -g -c main.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s


